// Generated by CoffeeScript 1.4.0
(function() {
  var Quiz,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Quiz = (function() {

    function Quiz(json) {
      this.next = __bind(this.next, this);

      this.setup_callbacks = __bind(this.setup_callbacks, this);

      this.play = __bind(this.play, this);

      this.start = __bind(this.start, this);
      this.json = json;
      this.setup_callbacks();
      this.start();
    }

    Quiz.prototype.start = function() {
      this.waiting = true;
      return $.getJSON(this.json, this.play);
    };

    Quiz.prototype.play = function(data) {
      var item, rnd_idx;
      this.data = data;
      $("#next").val("Solution");
      rnd_idx = Math.floor(Math.random() * data.length);
      item = this.data[rnd_idx];
      this.data.splice(rnd_idx, 1);
      $("#image_container").removeClass("night day").addClass(item.type);
      $("#image").attr('src', "images/" + item.image);
      return $("#solution").html(item.desc).hide();
    };

    Quiz.prototype.setup_callbacks = function() {
      $(document).on('click', '#next', this.next);
      return $(document).on('keydown', this.next);
    };

    Quiz.prototype.next = function() {
      if (this.waiting) {
        this.waiting = false;
        $("#next").val("Next (" + this.data.length + " left)");
        return $("#solution").show();
      } else {
        this.waiting = true;
        return this.play(this.data);
      }
    };

    return Quiz;

  })();

  $(function() {
    var quiz;
    return quiz = new Quiz('/images.json');
  });

}).call(this);
